[directory]
truncation_length = 8
truncation_symbol = ".../"
format = "at [$path]($style)[$read_only]($read_only_style) "
style = "bold blue"
read_only = "ğŸ”’"
read_only_style = "red"
home_symbol = "ğŸ  "

[aws]
format = "on [$symbol$profile]($style)"
style = "bold blue"
disabled = true

[cmd_duration]
format = "took â³ [$duration](bold yellow)"

[battery]
full_symbol = "ğŸ”‹ "
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ï–‚ "

[[battery.display]]
threshold = 10
style = "bold red"
discharging_symbol = "ğŸ’€ "

[[battery.display]]
threshold = 30
style = "bold yellow"
discharging_symbol = "ï•¼ "


[character]
success_symbol = "[âœ](bold green) "
error_symbol = "[âœ—](bold red) "

[username]
style_user = "cyan bold"
style_root = "red bold"
format = "ğŸ”¥ [$user]($style) "
disabled = false
show_always = true
